#! /usr/bin/env python

from chembddb.chembddb import run_config
import argparse

## Argument parser desription

parser = argparse.ArgumentParser(
    description=
    'This is a pacakge to generate a combinatorial library of molecules based on the building blocks provided. Please provide the building blocks in a file in either SMILES form or InChi, and the constraints in the config file.'
)
# parser.add_argument(
#     '-o',
#     "--option",
#     type=str,
#     default='all',
#     help="can be all,setup,insert or search")

## defining arguments
args = parser.parse_args()
# option = args.option

run_config()